name: thap
description: Thap app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: ^3.7.2

# to add run: flutter pub add package-name and then flutter pub get
dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.7
  flutter_svg: ^2.1.0
  get_it: ^8.0.3 
  country_code: ^1.1.0
  pretty_qr_code: ^3.4.0
  extra_hittest_area: ^1.0.0
  logger: ^2.5.0
  app_links: ^6.4.0
  oktoast: ^3.4.0
  http: ^1.4.0
  mime: ^2.0.0
  vibration: ^3.1.3
  devicelocale: ^0.8.1
  device_region: ^1.4.0
  flutter_widget_from_html_core: ^0.16.0
  collection: ^1.19.1
  photo_view: ^0.15.0
  form_builder_validators: ^11.1.2
  flutter_form_builder: ^10.0.1
  cached_network_image: ^3.4.1
  lazy_load_indexed_stack: ^1.2.1
  permission_handler: ^12.0.0+1 
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  share_plus: ^11.0.0
  flutter_hooks: ^0.21.2
  mobile_scanner: ^7.0.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  google_sign_in: ^6.3.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_inappwebview: ^6.1.5
  webview_flutter: ^4.12.0
  pdfx: ^2.9.1
  json_annotation: ^4.9.0
  gallery_saver_plus: ^3.2.4
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  mobx_codegen: ^2.1.1
  json_serializable: ^6.9.0 
  flutter_launcher_icons: ^0.14.3

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/search_logos/
    - assets/translations/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-SemiBold.ttf
    - family: Manrope-Bold
      fonts:
        - asset: assets/fonts/Manrope-ExtraBold.ttf
    - family: Manrope-Full
      fonts:
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/appicon-ios.png"
  image_path_android: "assets/appicon-android.png"
  adaptive_icon_foreground: "assets/appicon-android.png"
  adaptive_icon_background: "#ffffff"
